kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
spec:
  storageClassName: jenkins-pvc
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/jenkinspvc"
